# ========================================================
# PHP 构建参考流水线样例
# 功能：实现在构建中输出当前 PHP 构建环境的环境信息
# ========================================================
name: gitee-go-php-example            # 定义一个唯一 ID 标识为 gitee-go-php-example，名称为 “PHP-流水线示例” 的流水线
displayName: 'PHP-流水线示例'               
triggers:                             # 流水线触发器配置
  push:                               # 设置 master 分支 在产生代码 push 时精确触发（PRECISE）构建
    - matchType: PRECISE
      branch: master
commitMessage: ''                     # 通过匹配当前提交的 CommitMessage 决定是否执行流水线
stages:                               # 构建阶段配置
  - stage:                            # 定义一个 ID 标识为 php-build-stage，名为 “PHP Stage” 的阶段
      name: php-build-stage
      displayName: 'PHP Stage'
      failFast: false                 # 允许快速失败，即当 Stage 中有任务失败时，直接结束整个 Stage
      steps:                          # 构建步骤配置
        - step: phpbuild@1            # 采用 PHP 编译环境
          name: php-build             # 定义一个 ID 标识为 php-build ,名为 “PHP Step” 的阶段
          displayName: 'PHP Step'
          inputs:                     # 构建输入参数设定
            phpVersion: 8.0           # 指定 PHP 环境版本为 7.3
            goals: |                  # 示例脚本：创建 build 目录并输出 phpinfo 信息
              mkdir build
              echo '<?php phpinfo(); ?>' | php 2>&1